def generate_dags_file(dags: dict[str, dict]) -> str:
    """Generate a single Python file containing multiple DAGs."""
    imports = {"from airflow import DAG"}
    dag_blocks = []

    for dag_name, dag_config in dags.items():
        block, dag_imports = generate_dag_block(dag_name, dag_config)
        imports.update(dag_imports)
        dag_blocks.append(block)

    imports_str = "\n".join(sorted(imports))
    dags_str = "\n\n\n".join(dag_blocks)

    return f"""# Generated by dagfactory codegen — do not edit manually
{imports_str}


{dags_str}
"""


def generate_dag_block(dag_name: str, dag_config: dict) -> tuple[str, set]:
    """Generate a single DAG block and return it with its required imports."""
    tasks = dag_config.get("tasks", {})
    if isinstance(tasks, list):
        tasks = {task["task_id"]: {k: v for k, v in task.items() if k != "task_id"} for task in tasks}

    imports = set()
    for task_config in tasks.values():
        if task_config.get("decorator"):
            raise ValueError(
                "Tasks using 'decorator' (TaskFlow API) are not supported by generate — "
                "use the dagfactory runtime loader instead"
            )
        entry_point = task_config.get("operator")
        if not entry_point:
            raise ValueError("Tasks must define either 'operator' or 'decorator'")
        imports.add(get_operator_import(entry_point))

    tasks_code = []
    for task_name, task_config in tasks.items():
        tasks_code.append(generate_task_code(task_name, task_config))

    tasks_str = "\n\n    ".join(tasks_code)

    dag_params = [f'dag_id="df_{dag_name}"']
    skip_keys = {"tasks", "task_groups", "default_args"}
    for key, value in dag_config.items():
        if key in skip_keys:
            continue
        if key == "schedule" and isinstance(value, list) and all(isinstance(v, str) for v in value):
            imports.add("from airflow.sdk import Asset")
            assets_str = ", ".join(f"Asset({v!r})" for v in value)
            dag_params.append(f"schedule=[{assets_str}]")
        elif isinstance(value, str):
            dag_params.append(f'{key}="{value}"')
        else:
            dag_params.append(f"{key}={value!r}")

    dag_params_str = ",\n    ".join(dag_params)
    var_name = f"dag_{dag_name}"

    block = f"""# dag_id: df_{dag_name}
{var_name} = DAG(
    {dag_params_str},
)
with {var_name}:
    {tasks_str}"""

    return block, imports


def get_operator_import(operator_str: str) -> str:
    if "." not in operator_str:
        raise ValueError(
            f"Invalid operator '{operator_str}' must be a full path like 'airflow.operators.bash.BashOperator'"
        )
    module, class_name = operator_str.rsplit(".", 1)
    return f"from {module} import {class_name}"


def generate_task_code(task_name: str, task_config: dict) -> str:
    entry_point = task_config.get("operator") or task_config.get("decorator")
    _, class_name = entry_point.rsplit(".", 1)

    params = [f'task_id="{task_name}"']
    for key, value in task_config.items():
        if key not in ("operator", "decorator"):
            if isinstance(value, str):
                params.append(f'{key}="{value}"')
            else:
                params.append(f"{key}={value!r}")

    params_str = ",\n        ".join(params)
    return f"{task_name} = {class_name}(\n        {params_str},\n    )"
